In [1]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)
print('\n')
print(type(df))

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90


<class 'pandas.DataFrame'>

In [2]:
math1 = df['수학']
print(math1)
print('\n')
print(type(math1))

0    90
1    80
2    70
Name: 수학, dtype: int64


<class 'pandas.Series'>

In [3]:
english = df.영어
print(english)
print('\n')
print(type(english))

0    98
1    89
2    95
Name: 영어, dtype: int64


<class 'pandas.Series'>

In [4]:
music_gym = df[['음악', '체육']]
print(music_gym)
print('\n')
print(type(music_gym))

    음악   체육
0   85  100
1   95   90
2  100   90


<class 'pandas.DataFrame'>

In [5]:
math = df[['수학']]
print(math)
print('\n')
print(type(math))

   수학
0  90
1  80
2  70


<class 'pandas.DataFrame'>

In [8]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [9]:
df.iloc[0:3:2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [10]:
df.iloc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   85  100

In [1]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)

df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [2]:
a = df.loc['서준', '음악']
print(a)
b = df.iloc[0, 2]
print(b)

85
85

In [4]:
c = df.loc['서준', ['음악', '체육']]
print(c)
print(type(c))
d = df.iloc[0, [2, 3]]
print(d)
print(type(d))
e = df.loc['서준', '음악':'체육']
print(e)
print(type(e))
f = df.iloc[0, 2:]
print(f)
print(type(f))

음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [6]:
g = df.loc[['서준', '우현'], ['음악', '체육']]
print(g)
print(type(g))
h = df.iloc[[0, 1], [2, 3]]
print(h)
print(type(h))
i = df.loc['서준':'우현', '음악':'체육']
print(i)
print(type(i))
j = df.iloc[0:2, 2:]
print(j)
print(type(j))

    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>

In [7]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df['국어'] = 80
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [8]:
df['미술'] = [80, 90, 100]
print(df)

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [11]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)
print('\n')

df.loc[3] = 0
print(df)
print('\n')
df.loc[4] = ['동규', 90, 80, 70, 60]
print(df)
print('\n')
df.loc['행5'] = df.loc[3]
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90


   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0


   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60


    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [12]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df = df.set_index('이름')
print(df)

df.iloc[0][3] = 80
print(df)

df.loc['서준']['체육'] = 90
print(df)

df.loc['서준', '체육'] = 100
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

C:\Users\playdata2\AppData\Local\Temp\ipykernel_10652\1681079666.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.iloc[0][3] = 80
C:\Users\playdata2\AppData\Local\Temp\ipykernel_10652\1681079666.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc['서준']['체육'] = 90

In [13]:
df.loc['서준', ['음악','체육']] = 50
print(df)

df.loc['서준', ['음악','체육']] = 100, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [14]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df = df.transpose()
print(df)

df = df.T
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90
   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [15]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

ndf = df.set_index(['이름'])
print(ndf)

ndf2 = ndf.set_index('음악')
print(ndf2)

ndf3 = ndf.set_index(['수학', '음악'])
print(ndf3)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90
        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [16]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
print(ndf)

new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value=0)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [17]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index()
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [18]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index(names=['c00'])
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  c00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [19]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index(drop=True)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [2]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5,6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

ndf = df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

In [3]:
ndf2 = df.sort_index(ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [4]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5,6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.sort_values(by='c1', ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [5]:
ndf2 = df.sort_values(by='c2', ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [6]:
ndf3 = df.sort_values(by=['c3', 'c4'], ascending=[False, True])
print(ndf3)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [8]:
import pandas as pd

student1 = pd.Series({'국어':100, '영어':80, '수학':90})
print(student1)

percentage = student1/200

print(percentage)
print(type(percentage))

국어    100
영어     80
수학     90
dtype: int64
국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [9]:
import pandas as pd

student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

print(student1)
print('\n')
print(student2)

addition = student1 + student2
print(type(addition))
print(addition)

국어    100
영어     80
수학     90
dtype: int64


수학    80
국어    90
영어    80
dtype: int64
<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [11]:
subtraction = student1 - student2

print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [12]:
multiplication = student1 * student2
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [13]:
division = student1 / student2

print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [14]:
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [15]:
import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd. Series({'수학':80, '국어':90})

print(student1)
print(student2)

addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1/student2
print(type(division))
print('\n')

result = pd. DataFrame([addition, subtraction, multiplication, division],
                       index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
<class 'pandas.Series'>


     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [18]:
# Page 62, 예제1-24

import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd. Series({'수학':80, '국어':90})

print(student1)
print(student2)

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd. DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                       index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [1]:
# Page 64, 예제 1-25

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
print(df.head())
print('\n')
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


<class 'pandas.DataFrame'>

In [2]:
addition = df + 10
print(addition.head())
print('\n')
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


<class 'pandas.DataFrame'>

In [3]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
print(df.tail())
print('\n')
print(type(df))
print('\n')

addition = df + 10
print(addition.tail())
print('\n')
print(type(addition))
print('\n')

subtraction = addition - df
print(subtraction.tail())
print('\n')
print(type(subtraction))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75


<class 'pandas.DataFrame'>


      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75


<class 'pandas.DataFrame'>


      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0


<class 'pandas.DataFrame'>

In [4]:
sample1 = addition.tail()
sample2 = subtraction.tail().fillna(0.0)

print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [6]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)

print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [ ]:
# Page 70, 예제1-27
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[0:9, ['age','fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [2]:
df['age'] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [3]:
df[df['age'] < 20]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [4]:
df.loc[~(df['age'] < 20)]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [5]:
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [6]:
mask2 = (titanic.age < 10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [7]:
mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60  = titanic.loc[mask3, ['age', 'sex', 'alone']]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [8]:
df['age_under_20'] = df['age'] < 20
df.head()

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False

In [9]:
# Page 75, 예제 1-28

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic.loc[0:9, ['age', 'fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [10]:
df.query('age < 20')

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [11]:
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

In [12]:
df.query('age >= 20 or fare < 15')

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [14]:
# Page 78, 예제 1-29
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset('titanic')

pd.set_option('display.max_columns', 10)

mask1 = titanic['embark_town'] == "Southampton"
mask2 = titanic['embark_town'] == "Queenstown"
df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [16]:
isin_filter = titanic['embark_town'].isin(["Southampton",  "Queenstown"])
df_isin = titanic[isin_filter]
df_isin.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [18]:
# Page 80, 예제 1-30
import pandas as pd

fruit_names = pd.Series(["Apple", "Banana", "Cherry"])

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [19]:
pd.Series(["Apple", "Banana", "Cherry"], dtype="string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [21]:
pd.Series(["Apple", "Banana", "Cherry"], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [22]:
fruit_names.astype('string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [ ]:
# Page 82, 예제1-31
import pandas as pd
import numpy as np

ser = pd.Series(["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
                index=["First", "Second", "Third", "Fourth"])
                
print(ser)
print("\n")

ser2 = pd.Series(["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
                index=["First", "Second", "Third", "Fourth"], dtype="string")

print(ser2)

First       Apple_사과
Second    Banana_바나나
Third      Cherry_체리
Fourth           NaN
dtype: str


First       Apple_사과
Second    Banana_바나나
Third      Cherry_체리
Fourth          <NA>
dtype: string

In [24]:
print(ser.str.lower())
print("\n")

print(ser.str.upper())
print("\n")

print(ser.str.len())

First       apple_사과
Second    banana_바나나
Third      cherry_체리
Fourth           NaN
dtype: str


First       APPLE_사과
Second    BANANA_바나나
Third      CHERRY_체리
Fourth           NaN
dtype: str


First      8.0
Second    10.0
Third      9.0
Fourth     NaN
dtype: float64

In [25]:
print(ser.str.split("_"))
print("\n")

print(ser.str.split("_", expand=True))
print("\n")

print(ser.str.split("_").str.get(1))

First       [Apple, 사과]
Second    [Banana, 바나나]
Third      [Cherry, 체리]
Fourth              NaN
dtype: object


             0    1
First    Apple   사과
Second  Banana  바나나
Third   Cherry   체리
Fourth     NaN  NaN


First      사과
Second    바나나
Third      체리
Fourth    NaN
dtype: object

In [27]:
print(ser.str.replace("_", ":", regex=False))
print("\n")

print(ser.str.replace("[^a-zA-Z\s]", "", regex=True))

First       Apple:사과
Second    Banana:바나나
Third      Cherry:체리
Fourth           NaN
dtype: str


First      Apple
Second    Banana
Third     Cherry
Fourth       NaN
dtype: str

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
C:\Users\playdata2\AppData\Local\Temp\ipykernel_15864\1249770542.py:4: SyntaxWarning: invalid escape sequence '\s'
  print(ser.str.replace("[^a-zA-Z\s]", "", regex=True))

In [28]:
print(ser.str[0])
print("\n")

print(ser.str[0:4])

First       A
Second      B
Third       C
Fourth    NaN
dtype: str


First     Appl
Second    Bana
Third     Cher
Fourth     NaN
dtype: str

In [29]:
contains_A = ser.str.contains("A", na=False)
print(contains_A)
print("\n")

contains_pattern = ser.str.contains(r"[A|B][a-z]+")
print(contains_pattern)
print("\n")
fullmatch_pattern = ser.str.fullmatch(r"[A|B][a-z]+")
print(fullmatch_pattern)

First      True
Second    False
Third     False
Fourth    False
dtype: bool


First      True
Second     True
Third     False
Fourth    False
dtype: bool


First     False
Second    False
Third     False
Fourth    False
dtype: bool

In [31]:
ser3 = pd.Series(["a1", "b2", "c3", "d4a5", "e6e7", "f8"], dtype="string")

digits = ser3.str.extractall(r"(\d)").groupby(level=0).agg(''.join)
print(digits)
print("\n")

letters = ser3.str.extractall(r"([a-z])").groupby(level=0).agg(''.join)
print(letters)
print("\n")

split_columns = ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

    0
0   1
1   2
2   3
3  45
4  67
5   8


    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [ ]:
# Page 94, 예제 2-1
import pandas as pd
import os
os.listdir("./data")

['df_excelwriter.xlsx',
 'df_sample.csv',
 'df_sample.json',
 'df_sample.xlsx',
 'df_sample_columns.json',
 'df_sample_index.json',
 'df_sample_no_index.csv',
 'df_sample_no_index.xlsx',
 'df_sample_records.json',
 'df_sample_split.json',
 'df_sample_values.json',
 'read_csv_sample.csv',
 'read_json_sample.json',
 'sample.html',
 'test.csv',
 'test.json',
 '남북한발전전력량.xlsx']

In [35]:
file_path = './data/read_csv_sample.csv'

print(file_path)

file_path2 = os.path.join('data', 'read_csv_sample.csv')

print(file_path2)

./data/read_csv_sample.csv
data\read_csv_sample.csv

In [36]:
df1 = pd.read_csv(file_path)
print(df1)

df2 = pd.read_csv(file_path, header=None)
print(df2)

df3 = pd.read_csv(file_path, index_col=None)
print(df3)

df4 = pd.read_csv(file_path, index_col='c0')
print(df4)

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9
    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9
   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9
    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [37]:
# Page 98,예제 2-2
import pandas as pd
df1 = pd.read_excel('./data/남북한발전전력량.xlsx', engine='openpyxl')

df1.head()

  전력량 (억㎾h) 발전 전력별  1990  1991  1992  ...  2012  2013  2014  2015  2016
0        남한     합계  1077  1186  1310  ...  5096  5171  5220  5281  5404
1       NaN     수력    64    51    49  ...    77    84    78    58    66
2       NaN     화력   484   573   696  ...  3430  3581  3427  3402  3523
3       NaN    원자력   529   563   565  ...  1503  1388  1564  1648  1620
4       NaN    신재생     -     -     -  ...    86   118   151   173   195

[5 rows x 29 columns]

In [39]:
df2 = pd.read_excel('./data/남북한발전전력량.xlsx', engine='openpyxl', header=None)

df2.head()

          0       1     2     3     4   ...    24    25    26    27    28
0  전력량 (억㎾h)  발전 전력별  1990  1991  1992  ...  2012  2013  2014  2015  2016
1         남한      합계  1077  1186  1310  ...  5096  5171  5220  5281  5404
2        NaN      수력    64    51    49  ...    77    84    78    58    66
3        NaN      화력   484   573   696  ...  3430  3581  3427  3402  3523
4        NaN     원자력   529   563   565  ...  1503  1388  1564  1648  1620

[5 rows x 29 columns]