In [1]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)
print('\n')
print(type(df))

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90


<class 'pandas.DataFrame'>

In [2]:
math1 = df['수학']
print(math1)
print('\n')
print(type(math1))

0    90
1    80
2    70
Name: 수학, dtype: int64


<class 'pandas.Series'>

In [3]:
english = df.영어
print(english)
print('\n')
print(type(english))

0    98
1    89
2    95
Name: 영어, dtype: int64


<class 'pandas.Series'>

In [4]:
music_gym = df[['음악', '체육']]
print(music_gym)
print('\n')
print(type(music_gym))

    음악   체육
0   85  100
1   95   90
2  100   90


<class 'pandas.DataFrame'>

In [5]:
math = df[['수학']]
print(math)
print('\n')
print(type(math))

   수학
0  90
1  80
2  70


<class 'pandas.DataFrame'>

In [8]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [9]:
df.iloc[0:3:2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [10]:
df.iloc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   85  100

In [1]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)

df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [2]:
a = df.loc['서준', '음악']
print(a)
b = df.iloc[0, 2]
print(b)

85
85

In [4]:
c = df.loc['서준', ['음악', '체육']]
print(c)
print(type(c))
d = df.iloc[0, [2, 3]]
print(d)
print(type(d))
e = df.loc['서준', '음악':'체육']
print(e)
print(type(e))
f = df.iloc[0, 2:]
print(f)
print(type(f))

음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [6]:
g = df.loc[['서준', '우현'], ['음악', '체육']]
print(g)
print(type(g))
h = df.iloc[[0, 1], [2, 3]]
print(h)
print(type(h))
i = df.loc['서준':'우현', '음악':'체육']
print(i)
print(type(i))
j = df.iloc[0:2, 2:]
print(j)
print(type(j))

    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>
    음악   체육
이름
서준  85  100
우현  95   90
<class 'pandas.DataFrame'>

In [7]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df['국어'] = 80
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [8]:
df['미술'] = [80, 90, 100]
print(df)

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [11]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)
print('\n')

df.loc[3] = 0
print(df)
print('\n')
df.loc[4] = ['동규', 90, 80, 70, 60]
print(df)
print('\n')
df.loc['행5'] = df.loc[3]
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90


   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0


   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60


    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [12]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df = df.set_index('이름')
print(df)

df.iloc[0][3] = 80
print(df)

df.loc['서준']['체육'] = 90
print(df)

df.loc['서준', '체육'] = 100
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

C:\Users\playdata2\AppData\Local\Temp\ipykernel_10652\1681079666.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.iloc[0][3] = 80
C:\Users\playdata2\AppData\Local\Temp\ipykernel_10652\1681079666.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc['서준']['체육'] = 90

In [13]:
df.loc['서준', ['음악','체육']] = 50
print(df)

df.loc['서준', ['음악','체육']] = 100, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [14]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

df = df.transpose()
print(df)

df = df.T
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90
   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [15]:
import pandas as pd

exam_data = {'이름' : ['서준', '우현', '인아'],
                '수학' : [90, 80, 70],
                '영어' : [98, 89, 95],
                '음악' : [85, 95, 100],
                '체육' : [100, 90, 90]
}
df = pd.DataFrame(exam_data)
print(df)

ndf = df.set_index(['이름'])
print(ndf)

ndf2 = ndf.set_index('음악')
print(ndf2)

ndf3 = ndf.set_index(['수학', '음악'])
print(ndf3)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90
        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [16]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
print(ndf)

new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value=0)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [17]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index()
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [18]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index(names=['c00'])
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  c00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [19]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5, 6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.reset_index(drop=True)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [2]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5,6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
print(df)

ndf = df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

In [3]:
ndf2 = df.sort_index(ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [4]:
import pandas as pd

dict_data = {'c0':[1, 2, 3], 'c1':[4, 5,6], 'c2':[7, 8, 9], 'c3':[10, 11, 12], 'c4':[13, 14, 15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
print(df)

ndf = df.sort_values(by='c1', ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [5]:
ndf2 = df.sort_values(by='c2', ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [6]:
ndf3 = df.sort_values(by=['c3', 'c4'], ascending=[False, True])
print(ndf3)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [8]:
import pandas as pd

student1 = pd.Series({'국어':100, '영어':80, '수학':90})
print(student1)

percentage = student1/200

print(percentage)
print(type(percentage))

국어    100
영어     80
수학     90
dtype: int64
국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [9]:
import pandas as pd

student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

print(student1)
print('\n')
print(student2)

addition = student1 + student2
print(type(addition))
print(addition)

국어    100
영어     80
수학     90
dtype: int64


수학    80
국어    90
영어    80
dtype: int64
<class 'pandas.Series'>
국어    190
수학    170
영어    160
dtype: int64

In [11]:
subtraction = student1 - student2

print(type(subtraction))
print(subtraction)

<class 'pandas.Series'>
국어    10
수학    10
영어     0
dtype: int64

In [12]:
multiplication = student1 * student2
print(type(multiplication))
print(multiplication)

<class 'pandas.Series'>
국어    9000
수학    7200
영어    6400
dtype: int64

In [13]:
division = student1 / student2

print(type(division))
print(division)

<class 'pandas.Series'>
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [14]:
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
print(result)

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [15]:
import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd. Series({'수학':80, '국어':90})

print(student1)
print(student2)

addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1/student2
print(type(division))
print('\n')

result = pd. DataFrame([addition, subtraction, multiplication, division],
                       index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
<class 'pandas.Series'>


     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [18]:
# Page 62, 예제1-24

import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd. Series({'수학':80, '국어':90})

print(student1)
print(student2)

sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd. DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                       index=['덧셈', '뺄셈', '곱셈', '나눗셈'])

print(result)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64
       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf